![imagen](./img/ejercicios.png)

# Ejercicios Álgebra
## Ecuaciones lineales
Para la resolución de ejercicios tendrás que usar la función `linalg.solve` del módulo `numpy`:

```Python
A = np.array([[a, b],
              [c, d]])

b = np.array([e, f])

x = np.linalg.solve(A, b)

```

### Ejercicio 1
Encontrar dos números cuya suma sea 45 y cuya resta sea 21.

In [1]:
'''
x + y = 45
x - y = 21
'''

import numpy as np

A = np.array([[1, 1],
              [1, -1]])

b = np.array([45, 21])

x = np.linalg.solve(A, b)
x

array([33., 12.])

### Ejercicio 2
Hallar un número de dos cifras sabiendo que la suma de las cifras es 12 y que la primera de ellas es el triple de la segunda.

In [2]:
'''
x + y = 12
x = 3y
'''

A = np.array([[1, 1],
              [1, -3]])

b = np.array([12, 0])

x = np.linalg.solve(A, b)
x

array([9., 3.])

### Ejercicio 3
Alberto y su padre se llevan 25 años de edad. Calcular la edad de Alberto sabiendo que dentro de 15 años la edad de su padre será el doble que la suya.

In [3]:
'''
x + 25 = y
2*(x + 15) = (y + 15) ----> 2x = y - 15
'''

A = np.array([[1, -1],
              [2, -1]])

b = np.array([-25, -15])

x = np.linalg.solve(A, b)
x

array([10., 35.])

### Ejercicio 4
Hallar un número de tres cifras sabiendo que la suma de sus cifras es 11, que la suma de la primera y la tercera cifra es 5 y que la segunda cifra es el doble de la tercera.

In [4]:
'''
x + y + z = 11
x + z = 5
y = 2*z
'''

A = np.array([[1, 1, 1],
              [1, 0, 1],
              [0, 1, -2]])

b = np.array([11, 5, 0])

x = np.linalg.solve(A, b)
x

array([2., 6., 3.])

### Ejercicion 5
En un aula, la asignatura de gimnasia la han aprobado el 62,5% de las alumnas y el 80% de los alumnos, mientras que la asignatura de historia la han aprobado 87,5% de las alumnas y el 60% de los alumnos:

| |Gimnasia|Historia|
|----|----|----|
|Alumnas|62,5%|87,5%|
|Alumnos|80%|60%|
|Total|26|26|

In [5]:
'''
0.625x + 0.8y = 26
0.875x + 0.6y = 26
'''

A = np.array([[0.625, 0.8],
              [0.875, 0.6]])

b = np.array([26, 26])

x = np.linalg.solve(A, b)
x

array([16., 20.])