![imagen](../img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
my_array = np.arange(10)

my_array[::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:
my_array[8:6:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [5]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [11]:
my_matrix = np.arange(1, 21).reshape(4, 5)
my_matrix_2 = my_matrix.copy()

my_matrix_2 = np.flip(my_matrix_2)
my_matrix_2

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [12]:
my_matrix[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [13]:
my_matrix[::-1] # Como el axis = 0

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [15]:
my_matrix[::,::-1] # Como el axis = 1

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [17]:
my_matrix[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [20]:
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [22]:
print(my_matrix[:3:2, :5:2])
print(my_matrix[::2, ::2])

[[ 1  3  5]
 [11 13 15]]
[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [29]:
print(my_matrix[:-1:, ::-1])
print(my_matrix[[True, True, True, False]][::, ::-1])
print(np.flip(np.delete(my_matrix, -1, axis=0), axis=1))
print(my_matrix[:3:, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


In [30]:
fun = lambda x: np.flip(np.delete(x, -1, axis=0), axis=1)
fun(my_matrix)

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [31]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
mask_loro = x == "Loro"
print(x[mask_loro])

['Loro' 'Loro']


In [32]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x[::3])

['Loro' 'Loro']


In [33]:
filtro = np.array([1, 0, 0, 1, 0])
loros = x[filtro.astype(bool)]
print(loros)

['Loro' 'Loro']


In [34]:
np.array([1, 0, 0, 1, 0], dtype=bool)

array([ True, False, False,  True, False])

In [35]:
np.array([1, 0, 0, 1, 0], dtype=bool).astype(float)

array([1., 0., 0., 1., 0.])

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [36]:
np.arange(20).reshape((2, 5, 2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [42]:
my_matrix_0s = np.zeros(10, dtype=int)
print(my_matrix_0s)

print(my_matrix_0s.nbytes)

my_matrix_0s[3] = 1

print(my_matrix_0s)

[0 0 0 0 0 0 0 0 0 0]
40
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [50]:
my_vector = np.arange(10, 50)
print(my_vector[::-1])
print(np.flip(my_vector))
print(np.linspace(49, 10, num = 40, endpoint=True, dtype=int))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [57]:
my_vector_2 = np.array([1, 2] + [0]*2 + [4] + [0] ).reshape(2, -1)
print(my_vector_2)
row_nz, col_nz = np.nonzero(my_vector_2)
my_vector_2[row_nz, col_nz]

[[1 2 0]
 [0 4 0]]


array([1, 2, 4])

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [75]:
np.random.seed(1234)
my_rand_matrix = np.random.randint(100, size=(10, 10))
print(my_rand_matrix)

print(f"\nValor mínimo: {my_rand_matrix.min()}\nValor máximo: {my_rand_matrix.max()}")

[[47 83 38 53 76 24 15 49 23 26]
 [30 43 30 26 58 92 69 80 73 47]
 [50 76 37 34 38 67 11  0 75 80]
 [ 3  2 19 12 65 75 81 14 71 60]
 [46 28 81 87 13 96 12 69 95 31]
 [89 84 45 16 41 72 56 70 56 86]
 [44 90 83 47 49 18 85 46 98 37]
 [38  7 67  5 47 47 15 34 10 28]
 [ 4 82 89 55 78 23 50 62 55 84]
 [ 0 98 90 33 21 71 68 81 52 64]]

Valor mínimo: 0
Valor máximo: 98


In [66]:
np.random.rand(10, 10)

array([[0.69001621, 0.99057483, 0.69053432, 0.94812322, 0.58364465,
        0.53155327, 0.16865734, 0.15880774, 0.93796532, 0.71826456],
       [0.47654265, 0.88365336, 0.40420231, 0.17146805, 0.13183202,
        0.41190816, 0.02485604, 0.5635608 , 0.78187792, 0.26705997],
       [0.21425496, 0.17755704, 0.42926568, 0.97211312, 0.04653158,
        0.91735447, 0.15893009, 0.94338268, 0.76316153, 0.05387827],
       [0.25408163, 0.92797263, 0.8383115 , 0.15692453, 0.69077595,
        0.36694644, 0.93747272, 0.61336482, 0.69934982, 0.50294625],
       [0.7111109 , 0.13438585, 0.82893194, 0.74284587, 0.45703374,
        0.07910336, 0.37304659, 0.93363636, 0.41872481, 0.23421157],
       [0.57248483, 0.57211088, 0.41689298, 0.62588308, 0.22036227,
        0.62205913, 0.47767162, 0.97434208, 0.77298466, 0.02713854],
       [0.22102235, 0.12032832, 0.17527398, 0.42946156, 0.65776918,
        0.56589859, 0.56903498, 0.65419601, 0.36855768, 0.95238467],
       [0.19677048, 0.84993003, 0.9604582

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [98]:
# np.random.seed(1234)
my_vector_rand_2 = np.random.rand(30)
print(my_vector_rand_2)
print(my_vector_rand_2.mean())

[0.28587767 0.98674722 0.43180085 0.57423441 0.52724208 0.19765305
 0.16570843 0.50099046 0.99020406 0.39399181 0.71401327 0.17590427
 0.07069618 0.15762309 0.16155801 0.28363708 0.53670603 0.77323871
 0.88034358 0.63739145 0.85260224 0.59795537 0.69384666 0.53717667
 0.88923008 0.05226643 0.7831837  0.14517327 0.05869843 0.05899458]
0.470489637815658


In [115]:
for size in [10, 100, 1000, 10000, 10000000]:
    my_vector_rand_2 = np.random.rand(size)
    print(my_vector_rand_2.mean())

0.6587438234464982
0.4751934032888464
0.5011619874321755
0.5054550311512503
0.4998554938072538


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [124]:
a = np.full((8), 1)
b = np.array([[1,0,0,0,0,0,0,1]] * 6)
h = np.full((8), 1)
mi_array16 = np.vstack([a, b, h])
print(mi_array16)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [123]:
def matriz(filas, columnas):
    top_bottom = [1] * columnas
    inner_part = [[1] + [0] * (columnas - 2) + [1]] * (filas - 2)
    return [top_bottom, *inner_part, top_bottom]

def print_matriz(m):
    for fila in m:
        print(fila)
    print()
    
print_matriz(matriz(3,3))
print_matriz(matriz(4,5))

[1, 1, 1]
[1, 0, 1]
[1, 1, 1]

[1, 1, 1, 1, 1]
[1, 0, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 1, 1, 1, 1]



In [128]:
def matriz_gen(size):
    x = np.ones(size, dtype=int)
    x[1:-1:, 1:-1:] = 0
    return x

matriz_gen((10, 12))

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [141]:
ls_gen1 = [0, 1] 
ls_gen2 = [1, 0] 

n = 8

np.array([ls_gen1 * (n // 2) , ls_gen2 * (n // 2)] *(n // 2))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [142]:
a = np.array([0,1,0,1,0,1,0,1])
b = np.array([1,0,1,0,1,0,1,0])
mi_array17 = np.vstack([a,b] * 4)
print(mi_array17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [143]:
matrix_17 =np.full((8,8), 0)
matrix_17[1:8:2, 0:8:2]=1
matrix_17[0:8:2, 1:8:2]=1
print(matrix_17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [152]:
subm = np.array([[0, 1], [1, 0]])
np.tile(subm, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [155]:
a = np.array([0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0])
b = np.tile(a, 4)
mi_array18 = b.reshape(8, 8)
print(mi_array18)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [158]:
my_normal_matrix = np.random.normal(1000, 100, size=(5, 5))
print(my_normal_matrix)

my_normal_matrix_std = (my_normal_matrix - my_normal_matrix.mean()) / my_normal_matrix.std()
print(my_normal_matrix_std)

[[1006.53731647  888.46287808 1261.98729112 1098.66782739 1041.86449835]
 [1112.19522124 1086.94359846 1060.340617   1077.14020545 1135.48660232]
 [1113.89652121  778.55821825 1090.98469025  975.75953275  953.89724616]
 [1018.16565632  948.47173373 1061.03415965 1004.33619289 1068.76400578]
 [1083.31296566  964.07077857  861.13683122 1007.51755109 1007.58108566]]
[[-0.22536754 -1.44897931  2.42187432  0.72938592  0.14072995]
 [ 0.86957103  0.6078871   0.33219897  0.50629401  1.11094087]
 [ 0.88720169 -2.58792722  0.64976515 -0.54431937 -0.77087942]
 [-0.10486242 -0.8271043   0.33938619 -0.2481779   0.419491  ]
 [ 0.57026266 -0.66545056 -1.7321606  -0.21520931 -0.2145509 ]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [170]:
my_seq = np.arange(11)
my_seq_2 = my_seq.copy()

my_seq_2[3:9] = -1
print(my_seq_2)

mi_array10_2 = np.where((my_seq >= 3) & (my_seq <= 8), -1, my_seq)
print(mi_array10_2)

mi_array10_2[3:9] *= -1
mi_array10_2


[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


array([ 0,  1,  2,  1,  1,  1,  1,  1,  1,  9, 10])

## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [171]:
import numpy as np

In [42]:
# 1. Creación del tablero
arr_tab = np.full((10, 10), " ")
arr_tab

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [43]:
# 2. Posiciona dos barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]
arr_tab[:2, [1]] = "O"
arr_tab[[1], 3:7] = "O"
print(arr_tab)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [4]:
# 3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
arr_tab[np.where(arr_tab == "O")[0][0], np.where(arr_tab == "O")[1][0]] = "X"
print(arr_tab)

[[' ' 'X' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [5]:
# 4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
arr_tab[np.where(arr_tab != "O")[0][5], np.where(arr_tab != "O")[1][7]] = "_"
print(arr_tab)

[[' ' 'X' ' ' ' ' ' ' ' ' ' ' '_' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [22]:
np.all(np.full(10, ' ') != ' ')

False

In [24]:
list(range(4,5))

[4]

In [13]:
def is_water(arr, water=' '):
    return np.all(arr == water)

def place_boat(table, orig, size, orient):
    x_orig, y_orig = orig
    if orient == "E":
        size_x, size_y = 1, size
        
        try:
            arr_boat = table[[x_orig], list(range(y_orig, y_orig + size))]
            if is_water(arr_boat):
                arr_boat = "O"
            else:
                raise ValueError("Fuera del tablero")
        except:
            raise ValueError("Fuera del tablero")
    
    elif orient == "W":
        try:
            arr_boat = table[[x_orig], list(range(y_orig - size, y_orig))]
            if (y_orig - size >= 0)&(is_water(arr_boat)):
                arr_boat = "O"
            else:
                raise ValueError("Fuera del tablero")
        except:
            raise ValueError("Fuera del tablero")

    elif orient == "N":

        try:
            arr_boat = table[list(range(x_orig - size, x_orig)), [y_orig]]
            if (x_orig - size >= 0)&(is_water(arr_boat)):
                arr_boat = "O"
            else:
                raise ValueError("Fuera del tablero")
        except:
            raise ValueError("Fuera del tablero")
    
    elif orient == "S":
        try:
            arr_boat = table[list(range(x_orig, x_orig + size)), [y_orig]]
            if
            arr_boat = "O"
        except:
            raise ValueError("Fuera del tablero")

    else:
        raise ValueError("Orient not in [N, S, W, E]")
    
    return table


arr_example = arr_tab.copy()
place_boat(arr_example, (6, 7), 6, "W")
print(arr_example)
# arr_example

[[' ' 'X' ' ' ' ' ' ' ' ' ' ' '_' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' 'O' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [27]:
list(5:2)

SyntaxError: invalid syntax (2973904142.py, line 1)

In [55]:
def is_water(arr, water=' '):
    return np.all(arr == water)

def place_boat(table, orig, size, orient):
    x_orig, y_orig = orig
    if orient == "E":
        x_ext, y_ext = x_orig + 1, y_orig + size
    elif orient == "W":
        x_ext, y_ext = x_orig + 1, y_orig - size
    elif orient == "N":
        x_ext, y_ext = x_orig - size, y_orig + 1
    elif orient == "S":
        x_ext, y_ext = x_orig + size, y_orig + 1
    else:
        raise ValueError("Orient not in [N, S, W, E]")
    
    print(list(range(*sorted([x_orig, x_ext]))), list(range(*sorted([y_orig, y_ext]))))
    try:
        table[list(range(*sorted([x_orig, x_ext]))), list(range(*sorted([y_orig, y_ext])))] = "O"
        arr_boat = table[list(range(*sorted([x_orig, x_ext]))), list(range(*sorted([y_orig, y_ext])))]
    except:
        raise ValueError("Fuera del tablero")

    if (x_ext < 0)|(y_ext < 0)|(not is_water(arr_boat)):
        print("Cond x", (x_ext < 0))
        print("Cond y", (y_ext < 0))
        raise ValueError("Error de definición")
    return table


arr_example = arr_tab.copy()
place_boat(arr_example, (1, 4), 2, "W")
print(arr_example)
# arr_example

[1] [2, 3]
Cond x False
Cond y False
['O' 'O']


ValueError: Error de definición

In [50]:
is_water(arr_example[[[5], [2, 3]]])

C:\Users\alber\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


True

In [46]:
is_water(arr_example)

False

In [30]:
sorted([-4, 5])

[-4, 5]

In [31]:
list(range(*sorted([4, -5])))

[-5, -4, -3, -2, -1, 0, 1, 2, 3]

In [10]:
tuple(np.random.randint(10, size=2))

(3, 2)

In [19]:
# 5. Ignorando los disparos recibidos, ahora prueba a posicionar 
# otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**
import numpy as np
# np.random.seed(0)
random_pos = tuple(np.random.randint(10, size=2))
# print(random_pos, random_orient)
random_orient = np.random.choice(["N", "W", "E", "S"])


arr_prueba = arr_tab.copy()
while True:
    try:
        print(random_pos, random_orient)
        place_boat(arr_prueba, random_pos, 4, random_orient)
        break
    except:
        print(random_pos, random_orient)
        random_pos = tuple(np.random.randint(10, size=2))
        random_orient = np.random.choice(["N", "W", "E", "S"])
        print(random_pos, random_orient)

arr_prueba
# place_boat(arr_prueba, random_pos, 4, random_orient)

(0, 1) S


array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', '_', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')